apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: "/"
            pathType: prefix
            backend:
              service:
                name: client
                port:
                  number: 4200
          - path: "/api"
            pathType: prefix
            backend:
              service:
                name: api
                port: 
                  number: 5000
          - path: "/webapi"
            pathType: prefix
            backend:
              service:
                name: webapi
                port:
                  number: 9000
