apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
spec:
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
      - name: webapi
        image: 25795/webapi:v1
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
          name: webapi-port

