apiVersion: apps/v1
kind: Deployment
metadata:
  name: emysql
spec:
  selector:
    matchLabels:
      app: emysql
  template:
    metadata:
      labels:
        app: emysql
    spec:
      containers:
      - name: emysql
        image: mysql:8.0.33
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: emartdbpass
          - name: MYSQL_DATABASE
            value: books
        ports:
        - containerPort: 3306
          name: mysql-port
